// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyAvtEw_uqEOqGl2SQQCGMLmdR2wBvnvdA8',
      appId: '1:549754704175:web:73966b9bc408c89773d1da',
      messagingSenderId: '549754704175',
      projectId: 'roomease-74d55',
      authDomain: 'roomease-74d55.firebaseapp.com',
      storageBucket: 'roomease-74d55.appspot.com',
      measurementId: 'G-2W7SYHQPK8',
      databaseURL: 'https://roomease-74d55-default-rtdb.firebaseio.com');

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyApVs_6DF19yTxWYI4LOJrcL7SoaRX3qts',
      appId: '1:549754704175:android:f2d02cce66be595373d1da',
      messagingSenderId: '549754704175',
      projectId: 'roomease-74d55',
      storageBucket: 'roomease-74d55.appspot.com',
      databaseURL: 'https://roomease-74d55-default-rtdb.firebaseio.com');

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyCqBGxL0ASWeKQiKlBXK_9OwBnk9oNiYlw',
      appId: '1:549754704175:ios:b2f1f8ed569c710f73d1da',
      messagingSenderId: '549754704175',
      projectId: 'roomease-74d55',
      storageBucket: 'roomease-74d55.appspot.com',
      iosClientId:
          '549754704175-8h1auhrapdq4lbfmmaf84mnhqv50834o.apps.googleusercontent.com',
      iosBundleId: 'com.example.roomease',
      databaseURL: 'https://roomease-74d55-default-rtdb.firebaseio.com');

  static const FirebaseOptions macos = FirebaseOptions(
      apiKey: 'AIzaSyCqBGxL0ASWeKQiKlBXK_9OwBnk9oNiYlw',
      appId: '1:549754704175:ios:2bda3b7da08f4d3273d1da',
      messagingSenderId: '549754704175',
      projectId: 'roomease-74d55',
      storageBucket: 'roomease-74d55.appspot.com',
      iosClientId:
          '549754704175-fu6ni70qfp2m93fd6opodn75a044bo11.apps.googleusercontent.com',
      iosBundleId: 'com.example.roomease.RunnerTests',
      databaseURL: 'https://roomease-74d55-default-rtdb.firebaseio.com');
}
